[mqtt]
host = "nanomq"
port = 1883
client_id = "desmo"
topics = [
    "debug/diagnostics/#",
    "diagnostics/logs/+",
    "telemetry/#",
]
qos = 0

[database]
url = "postgresql://admin:admin@timescaledb:5432/metrics"
